
http.port=8081
prc.contentType = application/json
prc.client_secret =![QAhgyYajew1iqIa20D53tcBhv/32EbpHoMeO43rrSiCgGg28Z6qkyg==]
prc.client_id =![YZ+M9TD7XFZzYGZKFr6wsdptXFnRg+3k38PkAJlrGYYw3BLCVuPNMA==]

prc.create.method = POST
prc.get.method = GET

prc.url = https://mc-lead-prc-api-kd7ppn.9675fv.sgp-s1.cloudhub.io/api/leads

api.id = 20971887

# Anypoint MQ
mq.url=https://mq-us-east-1.anypoint.mulesoft.com/api/v1/organizations/02b32eab-24c3-4337-8ab2-3b89356e1a60/environments/c4f368bb-8edf-4594-9ccb-e9c12f75bb2e
mq.client.id=![x/hYsQLZNaf8LYI4I87Cks+1wM7iVgGb4EmKXnvjWobujHVyJeWIxg==]
mq.client.secret=![b9Hf+rMVhYXVW96S79AUbiim72mWHtl5qIatjtgtfRnGpxHshsyyEw==]

# Salesforce
sf.username=![Vj6Ggicny7yQM0CW71tqXXn/29J7ki7Lc7zQB83ZG+cCKvQlGD9lW8Lmn7oGOFLE]
sf.password=![vw8ENU2tY7o8SNs9wOhfM2eM9Kz/ksKR]
sf.security.token=![5jkxHWb7MzcuW+YH6CwCorGR24gg/gFlW6E+1734Y0Q=]
sf.auth.url=https://login.salesforce.com/services/Soap/u/59.0